services:
  frontend:
    container_name: frontend-sparehub
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_API_URL=${API_URL}
      - NODE_ENV=development
    networks:
      - app_net

  server:
    container_name: backend-sparehub
    build:
      context: ./backend/SpareHub
      dockerfile: Server/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - NEO4J_URL=${NEO4J_URL}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      - ./backend/SpareHub:/app
      - nuget_cache:/root/.nuget/packages
      - /app/Server/bin
      - /app/Server/obj
      - /app/Domain/bin
      - /app/Domain/obj
      - /app/Persistence/bin
      - /app/Persistence/obj
      - /app/Service/bin
      - /app/Service/obj
      - /app/Shared/bin
      - /app/Shared/obj

    depends_on:
      - mysql
      - mongodb
      - neo4j

    networks:
      - app_net

  mysql:
    image: mysql:8.0
    container_name: mysql-sparehub
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/mysql:/docker-entrypoint-initdb.d
    networks:
      - app_net

  mongodb:
    image: mongo:latest
    container_name: mongodb-sparehub
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./database/MongoDB:/docker-entrypoint-initdb.d
    networks:
      - app_net

  neo4j:
    image: neo4j:latest
    container_name: neo4j-sparehub
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./database/neo4j:/var/lib/neo4j/import
    networks:
      - app_net

volumes:
  mysql_data:
  nuget_cache:
  mongo_data:
  neo4j_data:

networks:
  app_net:
